### ISSUE TITLE
Improve Error handling

### ISSUE THREAD

**Issue by yongpingchen** [KiiPlatform/thing-if-JSSDK#67]
Abstract base error: GenericError, HttpError, NetworkError.
Detail errors describe as code

**Comment by satoshikumano** [comment]
After a consideration I found that there's not much difference when classifying error types by name or code(second level cluster) as long as number of logical class of errors is limited.

As we discussed, there's not many logical classes of error and we identified 'ArgumentError', 'HttpError', 'IlllegalStateError', and 'NetworkError'.
