### ISSUE TITLE
HttpError details

### ISSUE THREAD

**Issue by satoshikumano** [KiiPlatform/thing-if-JSSDK#69]
Question about body property details
- HttpError.body property is Object returned by Thing-IF?

If so, it would be good if it's typed since we can use code completion to get errorCode, errorMessage, etc.

- Sometimes body content-type is not json. (Ex. text/html when status is 5xx).

**Comment by yongpingchen** [comment]
body can be object 
```
{errorCode: string, message: string, rawData: string}
```
rawData is string of real response body.
