### ISSUE TITLE
ServerCodeTriggerRequest constructor

### ISSUE THREAD

**Issue by satoshikumano** [KiiPlatform/thing-if-JSSDK#73]
ServerCodeTriggerRequest arguments serverCode and predicate in constructor are optional?

https://github.com/KiiPlatform/thing-if-JSSDK/blob/develop/src/RequestObjects.ts#L262

**Comment by yongpingchen** [comment]
they are not optional. Need to fix

**Comment by satoshikumano** [comment]
fixed in #79
